/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Tools_Query.graphql
 * @generated SignedSource<<4ce3a36aab5c329eeba38b54fcd58175>>
 * @relayHash 311704d9c06028e2b8535f6f1a163bfe
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';

*/

/* eslint-disable comma-dangle, quotes */

/*
query Tools_Query {
  tools {
    ...Toolset_tools
  }
}

fragment Toolset_tools on Tools {
  toolset {
    url
    ...Tool_tool
  }
}

fragment Tool_tool on Tool {
  name
  summary
  url
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [],
    "kind": "Fragment",
    "metadata": null,
    "name": "Tools_Query",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "Tools",
        "name": "tools",
        "plural": false,
        "selections": [
          {
            "kind": "FragmentSpread",
            "name": "Toolset_tools",
            "args": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "Query"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "Tools_Query",
  "query": {
    "argumentDefinitions": [],
    "kind": "Root",
    "name": "Tools_Query",
    "operation": "query",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "Tools",
        "name": "tools",
        "plural": false,
        "selections": [
          {
            "kind": "LinkedField",
            "alias": null,
            "args": null,
            "concreteType": "Tool",
            "name": "toolset",
            "plural": true,
            "selections": [
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "url",
                "storageKey": null
              },
              {
                "kind": "InlineFragment",
                "type": "Tool",
                "selections": [
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": null,
                    "name": "name",
                    "storageKey": null
                  },
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": null,
                    "name": "summary",
                    "storageKey": null
                  }
                ]
              }
            ],
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ]
  },
  "text": "query Tools_Query {\n  tools {\n    ...Toolset_tools\n  }\n}\n\nfragment Toolset_tools on Tools {\n  toolset {\n    url\n    ...Tool_tool\n  }\n}\n\nfragment Tool_tool on Tool {\n  name\n  summary\n  url\n}\n"
};

module.exports = batch;
