/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Home_hello.flow
 * @generated SignedSource<<11ad51e8d737687a44c530a81ec3d06a>>
 * @flow
 */

'use strict';

export type Home_hello = {
  world?: ?string;
};
