/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Home_hello.graphql
 * @generated SignedSource<<f451e3d5136fd80b148c3845300f4810>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type Home_hello = {
  world?: ?string;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "Home_hello",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "world",
      "storageKey": null
    }
  ],
  "type": "HelloWorld"
};

module.exports = fragment;
