/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Toolset_tools.flow
 * @generated SignedSource<<59418efb9abe53f59364758a5b3a81a8>>
 * @flow
 */

'use strict';

export type Toolset_tools = {
  toolset?: ?Array<?Toolset_tools_toolset>;
};

export type Toolset_tools_toolset = {
  url?: ?string;
};
