/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Tools_tools.flow
 * @generated SignedSource<<11f4c57ebee16ad636ea19a73bae4366>>
 * @flow
 */

'use strict';

export type Tools_tools = {
  toolset?: ?Array<?any>;
};
