/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Tools_tools.graphql
 * @generated SignedSource<<4febc98a5dff6ae9039ffebd68bf53a2>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type Tools_tools = {
  toolset?: ?Array<?any>;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "Tools_tools",
  "selections": [
    {
      "kind": "LinkedField",
      "alias": null,
      "args": null,
      "concreteType": "Tool",
      "name": "toolset",
      "plural": true,
      "selections": [
        {
          "kind": "FragmentSpread",
          "name": "Tool_tool",
          "args": null
        }
      ],
      "storageKey": null
    }
  ],
  "type": "Tools"
};

module.exports = fragment;
