/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Tool_tool.graphql
 * @generated SignedSource<<5b7b04c55de1947ce34d038942d9330a>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type Tool_tool = {
  name?: ?string;
  summary?: ?string;
  url?: ?string;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "Tool_tool",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "name",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "summary",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "url",
      "storageKey": null
    }
  ],
  "type": "Tool"
};

module.exports = fragment;
