/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Tool_tool.flow
 * @generated SignedSource<<d048254a4ce5283ec195750e91efa1c0>>
 * @flow
 */

'use strict';

export type Tool_tool = {
  name?: ?string;
  summary?: ?string;
  url?: ?string;
};
